version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  build:
    working_directory: ~/momentum
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn
      - run:
          name: Tests
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
      - run:
          name: Build
          command: |
            yarn build:storybook

      - run:
          name: Installing deploy dependencies
          command: sudo apt-get -y -qq install awscli
      - deploy:
          name: Deploy
          command: |
            chmod +x ~/momentum/.circleci/deploy
            ~/momentum/.circleci/deploy
