version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    working_directory: ~/momentum
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: yarn
      - run:
          name: Tests
          command: yarn test
      - codecov/upload:
          file: coverage/*.json
      - run:
          name: Build
          command: |
            yarn build:storybook

      - run:
          name: Installing deploy dependencies
          command: sudo apt-get -y -qq install awscli
      - deploy:
          name: Deploy to master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync ~/momentum/storybook-static s3://momentum.somar.io  --region us-east-1 --delete
            fi
