#!/bin/bash

BRANCH_NORMALIZED="${CIRCLE_BRANCH//\//-}"

sync_bucket() {
  aws s3 sync ~/momentum/storybook-static $1 --region us-east-1 --delete
}

if [ "${CIRCLE_BRANCH}" == "master" ]; then
  echo "create and sync bucket to master"
  sync_bucket s3://momentum.somar.io
else
  # aws s3api head-bucket --bucket $BRANCH_NORMALIZED.momentum.somar.io || EXISTS=false
  # if [ $EXISTS ]; then

  if aws s3 ls "s3://$BRANCH_NORMALIZED.momentum.somar.io" 2>&1 | grep -q 'NoSuchBucket'; then
    echo "create and sync bucket"
    aws s3api create-bucket --bucket $BRANCH_NORMALIZED.momentum.somar.io --region us-east-1
    sync_bucket s3://$BRANCH_NORMALIZED.momentum.somar.io
  else
    echo "sync bucket"
    sync_bucket s3://$BRANCH_NORMALIZED.momentum.somar.io
  fi
fi
